import "server-only";

import { mapCampaignCategory } from "@/lib/campaigns/mappers";
import { resolveCampaignState } from "@/lib/campaigns/state";
import { createSupabaseAdminClient } from "@/lib/database/supabase/admin";
import { createSupabaseServerClient } from "@/lib/database/supabase/server";
import { env } from "@/lib/env/server";
import { buildCommunityHostname } from "@/lib/communities/hostname";
import { hashIpFingerprint, hashVerifiedEmail } from "@/lib/nominations/privacy";
import { recordFraudSignal } from "@/lib/nominations/service";
import { mapFinalist, mapVote, toPublicFinalistView } from "@/lib/voting/mappers";
import {
  evaluateVoteEligibility,
  proposeFinalistsFromNominations,
  publicVotePresence,
  voteRuleMessage,
  type VoteRuleFailure,
} from "@/lib/voting/rules";
import type { Campaign } from "@/types/campaign";
import type {
  Finalist,
  PublicFinalistView,
  PublicVoteProgress,
  Vote,
  VoteEventType,
} from "@/types/voting";

export { publicVotePresence };

async function recordVoteEvent(
  voteId: string,
  eventType: VoteEventType,
  metadata: Record<string, string | number | boolean | null> = {},
) {
  const admin = createSupabaseAdminClient();
  await admin.from("vote_events").insert({
    vote_id: voteId,
    event_type: eventType,
    metadata,
  });
}

async function countValidNominations(
  campaignId: string,
  campaignCategoryId: string,
  businessLocationId: string,
): Promise<number> {
  const admin = createSupabaseAdminClient();
  const { count } = await admin
    .from("nominations")
    .select("id", { count: "exact", head: true })
    .eq("campaign_id", campaignId)
    .eq("campaign_category_id", campaignCategoryId)
    .eq("business_location_id", businessLocationId)
    .eq("status", "valid");
  return count ?? 0;
}

export async function generateProposedFinalists(input: {
  campaignId: string;
  campaignCategoryId?: string | null;
  actorUserId: string;
}): Promise<{ ok: boolean; message: string; created: number }> {
  const admin = createSupabaseAdminClient();
  let categoryQuery = admin
    .from("campaign_categories")
    .select("*")
    .eq("campaign_id", input.campaignId)
    .eq("active", true);
  if (input.campaignCategoryId) {
    categoryQuery = categoryQuery.eq("id", input.campaignCategoryId);
  }
  const { data: categories } = await categoryQuery;
  if (!categories?.length) {
    return { ok: false, message: "No active categories found.", created: 0 };
  }

  let created = 0;
  for (const categoryRow of categories) {
    const category = mapCampaignCategory(categoryRow);
    const { data: nominations } = await admin
      .from("nominations")
      .select("business_location_id")
      .eq("campaign_id", input.campaignId)
      .eq("campaign_category_id", category.id)
      .eq("status", "valid")
      .not("business_location_id", "is", null);

    const counts = new Map<string, number>();
    for (const row of nominations ?? []) {
      if (!row.business_location_id) continue;
      counts.set(row.business_location_id, (counts.get(row.business_location_id) ?? 0) + 1);
    }

    const proposed = proposeFinalistsFromNominations(
      [...counts.entries()].map(([businessLocationId, validNominationCount]) => ({
        businessLocationId,
        validNominationCount,
      })),
      {
        finalistLimit: category.finalistLimit,
        minimumNominationCount: category.minimumNominationCount,
      },
    );

    // Soft-remove previous automatic proposals that are not in the new set.
    const keepIds = new Set(proposed.map((item) => item.businessLocationId));
    const { data: existing } = await admin
      .from("finalists")
      .select("*")
      .eq("campaign_id", input.campaignId)
      .eq("campaign_category_id", category.id)
      .in("status", ["proposed"]);

    for (const row of existing ?? []) {
      if (!keepIds.has(row.business_location_id) && row.selection_method === "automatic") {
        await admin
          .from("finalists")
          .update({
            status: "removed",
            removal_reason: "Replaced by regenerated automatic proposal",
            admin_notes: `Regenerated by ${input.actorUserId}`,
          })
          .eq("id", row.id);
      }
    }

    for (const candidate of proposed) {
      const { data: current } = await admin
        .from("finalists")
        .select("id, status")
        .eq("campaign_id", input.campaignId)
        .eq("campaign_category_id", category.id)
        .eq("business_location_id", candidate.businessLocationId)
        .in("status", ["proposed", "approved", "published"])
        .maybeSingle();

      if (current) {
        continue;
      }

      const { error } = await admin.from("finalists").insert({
        campaign_id: input.campaignId,
        campaign_category_id: category.id,
        business_location_id: candidate.businessLocationId,
        selection_method: "automatic",
        status: "proposed",
        selected_by: input.actorUserId,
        selected_at: new Date().toISOString(),
        admin_notes: "Generated from valid nominations",
      });
      if (!error) {
        created += 1;
      }
    }
  }

  return {
    ok: true,
    message: `Proposed ${created} finalist${created === 1 ? "" : "s"}.`,
    created,
  };
}

export async function approveFinalist(input: {
  finalistId: string;
  actorUserId: string;
}): Promise<{ ok: boolean; message: string }> {
  const admin = createSupabaseAdminClient();
  const { data: finalist } = await admin
    .from("finalists")
    .select("*")
    .eq("id", input.finalistId)
    .maybeSingle();
  if (!finalist || finalist.status === "removed") {
    return { ok: false, message: "Finalist not found." };
  }

  const snapshot = await countValidNominations(
    finalist.campaign_id,
    finalist.campaign_category_id,
    finalist.business_location_id,
  );

  const { error } = await admin
    .from("finalists")
    .update({
      status: "approved",
      nomination_count_snapshot: snapshot,
      selected_at: new Date().toISOString(),
      selected_by: input.actorUserId,
    })
    .eq("id", input.finalistId);

  return {
    ok: !error,
    message: error ? "Unable to approve finalist." : "Finalist approved with frozen nomination snapshot.",
  };
}

export async function removeFinalist(input: {
  finalistId: string;
  actorUserId: string;
  reason: string;
}): Promise<{ ok: boolean; message: string }> {
  const admin = createSupabaseAdminClient();
  const { error } = await admin
    .from("finalists")
    .update({
      status: "removed",
      removal_reason: input.reason,
      admin_notes: `Removed by ${input.actorUserId}`,
      selected_by: input.actorUserId,
      selected_at: new Date().toISOString(),
    })
    .eq("id", input.finalistId)
    .neq("status", "removed");

  return {
    ok: !error,
    message: error ? "Unable to remove finalist." : "Finalist removed.",
  };
}

export async function manualAddFinalist(input: {
  campaignId: string;
  campaignCategoryId: string;
  businessLocationId: string;
  actorUserId: string;
  notes: string;
}): Promise<{ ok: boolean; message: string }> {
  const admin = createSupabaseAdminClient();
  const { data: location } = await admin
    .from("business_locations")
    .select("id, community_id, active, deleted_at, businesses!inner(status, deleted_at)")
    .eq("id", input.businessLocationId)
    .maybeSingle();

  if (!location || location.deleted_at || !location.active) {
    return { ok: false, message: "Business location is not eligible." };
  }

  const { data: campaign } = await admin
    .from("campaigns")
    .select("community_id")
    .eq("id", input.campaignId)
    .maybeSingle();
  if (!campaign || campaign.community_id !== location.community_id) {
    return { ok: false, message: "Location is outside this campaign community." };
  }

  const snapshot = await countValidNominations(
    input.campaignId,
    input.campaignCategoryId,
    input.businessLocationId,
  );

  const { error } = await admin.from("finalists").insert({
    campaign_id: input.campaignId,
    campaign_category_id: input.campaignCategoryId,
    business_location_id: input.businessLocationId,
    selection_method: "manual",
    status: "proposed",
    nomination_count_snapshot: null,
    selected_by: input.actorUserId,
    selected_at: new Date().toISOString(),
    admin_notes: `${input.notes} (valid nominations at add: ${snapshot})`,
  });

  if (error?.code === "23505") {
    return { ok: false, message: "That business is already a finalist in this category." };
  }

  return {
    ok: !error,
    message: error ? "Unable to add finalist." : "Finalist added manually for review.",
  };
}

export async function publishFinalists(input: {
  campaignId: string;
  actorUserId: string;
}): Promise<{ ok: boolean; message: string; published: number }> {
  const admin = createSupabaseAdminClient();

  // Freeze snapshots for any approved rows missing them, then publish approved.
  const { data: approved } = await admin
    .from("finalists")
    .select("*")
    .eq("campaign_id", input.campaignId)
    .eq("status", "approved");

  for (const row of approved ?? []) {
    let snapshot = row.nomination_count_snapshot;
    if (snapshot === null) {
      snapshot = await countValidNominations(
        row.campaign_id,
        row.campaign_category_id,
        row.business_location_id,
      );
    }
    await admin
      .from("finalists")
      .update({
        status: "published",
        nomination_count_snapshot: snapshot,
        selected_by: input.actorUserId,
        selected_at: new Date().toISOString(),
      })
      .eq("id", row.id);
  }

  return {
    ok: true,
    message: `Published ${approved?.length ?? 0} finalist(s).`,
    published: approved?.length ?? 0,
  };
}

export async function listAdminFinalists(campaignId: string): Promise<Finalist[]> {
  const admin = createSupabaseAdminClient();
  const { data } = await admin
    .from("finalists")
    .select("*")
    .eq("campaign_id", campaignId)
    .order("created_at", { ascending: false })
    .limit(300);
  return (data ?? []).map(mapFinalist);
}

export async function listPublishedFinalists(input: {
  campaign: Campaign;
  communityId: string;
  categorySlug?: string;
}): Promise<PublicFinalistView[]> {
  const state = resolveCampaignState(input.campaign);
  if (!state.canPublicReadCampaign) {
    return [];
  }

  try {
    const supabase = await createSupabaseServerClient();
    const query = supabase
      .from("finalists")
      .select(
        `
        id,
        campaign_category_id,
        business_location_id,
        campaign_categories (
          local_name,
          local_slug,
          active,
          master_categories ( name, slug, category_groups ( name ) )
        ),
        business_locations!inner (
          location_name,
          community_id,
          slug,
          businesses!inner (
            public_name,
            slug,
            logo_url,
            status,
            deleted_at
          )
        )
      `,
      )
      .eq("campaign_id", input.campaign.id)
      .eq("status", "published")
      .eq("business_locations.community_id", input.communityId);

    const { data } = await query;
    if (!data) {
      return [];
    }

    return data.flatMap((row) => {
      const category = row.campaign_categories as unknown as {
        local_name: string | null;
        local_slug: string | null;
        active: boolean;
        master_categories: {
          name: string;
          slug: string;
          category_groups: { name: string } | null;
        } | null;
      } | null;
      const location = row.business_locations as unknown as {
        location_name: string;
        community_id: string;
        slug: string;
        businesses: {
          public_name: string;
          slug: string;
          logo_url: string | null;
          status: string;
          deleted_at: string | null;
        };
      };

      if (!category?.active || location.businesses.deleted_at || location.businesses.status !== "approved") {
        return [];
      }

      const categorySlug =
        category.local_slug || category.master_categories?.slug || "category";
      if (input.categorySlug && categorySlug !== input.categorySlug) {
        return [];
      }

      return [
        toPublicFinalistView({
          finalistId: row.id,
          categoryId: row.campaign_category_id,
          categoryName: category.local_name || category.master_categories?.name || "Category",
          categorySlug,
          groupName: category.master_categories?.category_groups?.name || "Categories",
          businessName: location.businesses.public_name,
          businessSlug: location.businesses.slug,
          locationName: location.location_name,
          logoUrl: location.businesses.logo_url,
        }),
      ];
    });
  } catch {
    return [];
  }
}

export type CastVoteResult =
  | { ok: true; voteId: string; changed: boolean }
  | { ok: false; reason: VoteRuleFailure | "rate_limited" | "server_error"; message: string };

export async function castOrChangeVote(input: {
  campaign: Campaign;
  communityId: string;
  userId: string;
  email: string;
  emailConfirmed: boolean;
  campaignCategoryId: string;
  finalistId: string;
  ipAddress?: string | null;
}): Promise<CastVoteResult> {
  const campaignState = resolveCampaignState(input.campaign);
  const admin = createSupabaseAdminClient();

  const { data: category } = await admin
    .from("campaign_categories")
    .select("id, campaign_id, active")
    .eq("id", input.campaignCategoryId)
    .eq("campaign_id", input.campaign.id)
    .maybeSingle();

  const { data: finalist } = await admin
    .from("finalists")
    .select(
      `
      id,
      campaign_id,
      campaign_category_id,
      status,
      business_location_id,
      business_locations ( community_id )
    `,
    )
    .eq("id", input.finalistId)
    .maybeSingle();

  const locationCommunityId = (
    finalist?.business_locations as unknown as { community_id: string } | null
  )?.community_id;

  const eligibility = evaluateVoteEligibility({
    emailConfirmed: input.emailConfirmed,
    campaignState,
    votingLocked: campaignState.votingLocked,
    categoryBelongsToCampaign: Boolean(category),
    categoryActive: Boolean(category?.active),
    finalistExists: Boolean(finalist),
    finalistPublished: finalist?.status === "published",
    finalistBelongsToCategory: finalist?.campaign_category_id === input.campaignCategoryId,
    finalistInCommunity: locationCommunityId === input.communityId,
  });

  if (!eligibility.ok) {
    const signalType =
      eligibility.reason === "unverified_user"
        ? "unverified_user"
        : eligibility.reason === "voting_closed" || eligibility.reason === "voting_locked"
          ? "closed_phase_attempt"
          : eligibility.reason === "cross_community"
            ? "cross_community_attempt"
            : "manual_review";

    await recordFraudSignal({
      campaignId: input.campaign.id,
      entityType: "user",
      entityId: input.userId,
      signalType,
      riskScore: 40,
      metadata: {
        reason: eligibility.reason,
        ipHash: input.ipAddress ? hashIpFingerprint(input.ipAddress) : null,
        finalistId: input.finalistId,
      },
    });

    return {
      ok: false,
      reason: eligibility.reason,
      message: voteRuleMessage(eligibility.reason),
    };
  }

  const { data: existing } = await admin
    .from("votes")
    .select("*")
    .eq("campaign_id", input.campaign.id)
    .eq("campaign_category_id", input.campaignCategoryId)
    .eq("user_id", input.userId)
    .eq("status", "active")
    .maybeSingle();

  if (existing) {
    if (existing.finalist_id === input.finalistId) {
      return { ok: true, voteId: existing.id, changed: false };
    }

    const { data: updated, error } = await admin
      .from("votes")
      .update({ finalist_id: input.finalistId })
      .eq("id", existing.id)
      .eq("status", "active")
      .select("*")
      .maybeSingle();

    if (error || !updated) {
      return { ok: false, reason: "server_error", message: "Unable to change vote." };
    }

    await recordVoteEvent(updated.id, "changed", {
      previousFinalistId: existing.finalist_id,
      nextFinalistId: input.finalistId,
    });

    return { ok: true, voteId: updated.id, changed: true };
  }

  const { data: created, error } = await admin
    .from("votes")
    .insert({
      campaign_id: input.campaign.id,
      campaign_category_id: input.campaignCategoryId,
      finalist_id: input.finalistId,
      user_id: input.userId,
      verified_email_hash: hashVerifiedEmail(input.email),
      status: "active",
    })
    .select("*")
    .maybeSingle();

  if (error || !created) {
    if (error?.code === "23505") {
      return {
        ok: false,
        reason: "server_error",
        message: "You already have an active vote in this category.",
      };
    }
    return { ok: false, reason: "server_error", message: "Unable to save vote." };
  }

  await recordVoteEvent(created.id, "created", { finalistId: input.finalistId });
  return { ok: true, voteId: created.id, changed: false };
}

export async function invalidateVote(input: {
  voteId: string;
  actorUserId: string;
  reason: string;
}): Promise<{ ok: boolean; message: string }> {
  const admin = createSupabaseAdminClient();
  const { data, error } = await admin
    .from("votes")
    .update({
      status: "invalidated",
      invalidated_at: new Date().toISOString(),
      invalidated_by: input.actorUserId,
      invalidation_reason: input.reason,
    })
    .eq("id", input.voteId)
    .eq("status", "active")
    .select("*")
    .maybeSingle();

  if (error || !data) {
    return { ok: false, message: "Unable to invalidate vote." };
  }

  await recordVoteEvent(data.id, "invalidated", {
    reason: input.reason,
    actorUserId: input.actorUserId,
  });

  await recordFraudSignal({
    campaignId: data.campaign_id,
    entityType: "vote",
    entityId: data.id,
    signalType: "manual_review",
    riskScore: 60,
    metadata: { reason: input.reason },
  });

  return { ok: true, message: "Vote invalidated." };
}

export async function lockVoting(input: {
  campaignId: string;
  lock: boolean;
}): Promise<{ ok: boolean; message: string }> {
  const admin = createSupabaseAdminClient();
  const { error } = await admin
    .from("campaigns")
    .update({
      voting_locked_at: input.lock ? new Date().toISOString() : null,
      status: input.lock ? "voting_closed" : "voting_open",
    })
    .eq("id", input.campaignId);

  return {
    ok: !error,
    message: error
      ? "Unable to update voting lock."
      : input.lock
        ? "Voting locked."
        : "Voting unlocked.",
  };
}

export async function listUserVoteProgress(input: {
  userId: string;
  campaignId: string;
  categories: Array<{ id: string; displaySlug: string; displayName: string }>;
}): Promise<PublicVoteProgress[]> {
  const supabase = await createSupabaseServerClient();
  const { data } = await supabase
    .from("votes")
    .select("campaign_category_id, finalist_id")
    .eq("user_id", input.userId)
    .eq("campaign_id", input.campaignId)
    .eq("status", "active");

  const byCategory = new Map(
    (data ?? []).map((row) => [row.campaign_category_id, row.finalist_id]),
  );

  return input.categories.map((category) => ({
    categoryId: category.id,
    categorySlug: category.displaySlug,
    categoryName: category.displayName,
    voted: byCategory.has(category.id),
    selectedFinalistId: byCategory.get(category.id) ?? null,
  }));
}

export async function getUserActiveVoteForCategory(input: {
  userId: string;
  campaignId: string;
  campaignCategoryId: string;
}): Promise<Vote | null> {
  const supabase = await createSupabaseServerClient();
  const { data } = await supabase
    .from("votes")
    .select("*")
    .eq("user_id", input.userId)
    .eq("campaign_id", input.campaignId)
    .eq("campaign_category_id", input.campaignCategoryId)
    .eq("status", "active")
    .maybeSingle();
  return data ? mapVote(data) : null;
}

export function buildVoteShareUrl(input: {
  communitySubdomain: string;
  categorySlug?: string | null;
}): string {
  const protocol = env.NEXT_PUBLIC_APP_URL.startsWith("https") ? "https" : "http";
  const origin = buildCommunityHostname(
    input.communitySubdomain,
    env.NEXT_PUBLIC_ROOT_DOMAIN,
    protocol,
  );
  if (input.categorySlug) {
    return `${origin}/vote/${input.categorySlug}`;
  }
  return `${origin}/vote`;
}

export async function getBusinessFinalistPresence(input: {
  businessId: string;
  campaignId: string;
}): Promise<{ presence: "none" | "finalist"; locationIds: string[]; finalistIds: string[] }> {
  const supabase = await createSupabaseServerClient();
  const { data: locations } = await supabase
    .from("business_locations")
    .select("id")
    .eq("business_id", input.businessId)
    .is("deleted_at", null);

  const locationIds = (locations ?? []).map((row) => row.id);
  if (!locationIds.length) {
    return { presence: "none", locationIds: [], finalistIds: [] };
  }

  const { data: finalists } = await supabase
    .from("finalists")
    .select("id")
    .eq("campaign_id", input.campaignId)
    .eq("status", "published")
    .in("business_location_id", locationIds);

  const finalistIds = (finalists ?? []).map((row) => row.id);
  return {
    presence: finalistIds.length ? "finalist" : "none",
    locationIds,
    finalistIds,
  };
}

export async function listAdminVotes(campaignId: string): Promise<Vote[]> {
  const admin = createSupabaseAdminClient();
  const { data } = await admin
    .from("votes")
    .select("*")
    .eq("campaign_id", campaignId)
    .order("created_at", { ascending: false })
    .limit(200);
  return (data ?? []).map(mapVote);
}

export async function listInvalidatedVotes(campaignId: string): Promise<Vote[]> {
  const admin = createSupabaseAdminClient();
  const { data } = await admin
    .from("votes")
    .select("*")
    .eq("campaign_id", campaignId)
    .eq("status", "invalidated")
    .order("invalidated_at", { ascending: false })
    .limit(150);
  return (data ?? []).map(mapVote);
}

export async function getVotingActivity(campaignId: string): Promise<
  Array<{ campaignCategoryId: string; activeVotes: number; invalidatedVotes: number }>
> {
  const admin = createSupabaseAdminClient();
  const { data } = await admin
    .from("votes")
    .select("campaign_category_id, status")
    .eq("campaign_id", campaignId);

  const map = new Map<
    string,
    { campaignCategoryId: string; activeVotes: number; invalidatedVotes: number }
  >();

  for (const row of data ?? []) {
    const current = map.get(row.campaign_category_id) ?? {
      campaignCategoryId: row.campaign_category_id,
      activeVotes: 0,
      invalidatedVotes: 0,
    };
    if (row.status === "active") current.activeVotes += 1;
    if (row.status === "invalidated") current.invalidatedVotes += 1;
    map.set(row.campaign_category_id, current);
  }

  return [...map.values()];
}

export async function buildVotingAuditReport(campaignId: string): Promise<string> {
  const [finalists, votes, activity] = await Promise.all([
    listAdminFinalists(campaignId),
    listAdminVotes(campaignId),
    getVotingActivity(campaignId),
  ]);

  const lines = [
    `Voting audit report for campaign ${campaignId}`,
    `Generated at ${new Date().toISOString()}`,
    "",
    `Finalists: ${finalists.length}`,
    `  proposed=${finalists.filter((f) => f.status === "proposed").length}`,
    `  approved=${finalists.filter((f) => f.status === "approved").length}`,
    `  published=${finalists.filter((f) => f.status === "published").length}`,
    `  removed=${finalists.filter((f) => f.status === "removed").length}`,
    "",
    `Votes: ${votes.length}`,
    `  active=${votes.filter((v) => v.status === "active").length}`,
    `  invalidated=${votes.filter((v) => v.status === "invalidated").length}`,
    "",
    "Category activity:",
    ...activity.map(
      (row) =>
        `  ${row.campaignCategoryId}: active=${row.activeVotes} invalidated=${row.invalidatedVotes}`,
    ),
    "",
    "Note: Exact public vote totals must remain hidden until results are published.",
  ];

  return lines.join("\n");
}
